name: Push to Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/actions/build

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        uses: ./.github/actions/unit-tests

  e2e-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: E2E Tests
        uses: ./.github/actions/e2e-tests