name: Push to Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/build

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/unit-tests

  e2e-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/e2e-tests